### ISSUE TITLE
Relay Switching

### ISSUE THREAD

**Issue by hkauroberoi** [ArnieX/swifitch-software#2]
Hello,

Finally all the components arrived and I could assemble the board !! Works fine and the image is attached. The soldering is very poor but that's the best I could do :)

I'm not able to figure out how to connect the existing wall switch on the board? Please guide me a bit. 

Noticed following issues -

1. With the NODEMCU as programmer, I could not upload the code and repeatedly got error message espcomm_send_command: wrong direction/command or espcomm sync failure. CP2102 worked fine.

2. At times the command to turn off misfires and it instead turn on the load - but i suspect that the relay is faulty (chinese relay). Did you encountered such issue? Will update soon with genuine Songle relay and few more boards that I'll assemble. 

![switchb](https://user-images.githubusercontent.com/32226302/32405753-50337f02-c191-11e7-8d3e-0a8a5daad8e6.png)

**Comment by ArnieX** [comment]
Hi,

thanks a lot for sharing.

1, Not sure what's up with NodeMCU, good to know that CP2102 did it for you.

2, Never happened to me.

For analog switch, first enable this function in source code and flash again. After that connect 3V to analog switch IN, and OUT to D2 pin on swifitch, then bridge D2 and GND with resistor, if I remember well it was 10K. This will pulldown D2 when 3V are disconnected from analog switch.

Hope this helps, let me know.

**Comment by hkauroberoi** [comment]
Thanks and sorry for the delayed update. The analog switch works absolutely fine when wired as you suggested - in fact the module works flawlessly now - kids are happy :))

Another update - just now I connected an antique rotating table fan (80 Watt with 3 different manual speed buttons) to the module and noticed that when used at lowest speed, the relay starts to flicker badly. The relay is tested and absolutely fine so yet to see what's causing this - **please let me know if you ever faced such issue with inductive load.**

![fanpanel](https://user-images.githubusercontent.com/32226302/32843590-24edd9c4-ca46-11e7-91c4-d06a9de6cd61.png)
![fanspec](https://user-images.githubusercontent.com/32226302/32843591-2534279e-ca46-11e7-9b1b-f9cf2d4d5127.png)

.

**Comment by ArnieX** [comment]
Hi,

I'm happy to hear that it works well now. For the flickering I have never experienced that, but it's true that I have only ever used swifitch for switching single or multiple LED bulbs.

BR,

Martin

**Comment by hkauroberoi** [comment]
Thank you so much.... I'll post an update once the issue is addressed - might help someone someday !!

Appreciate your efforts.

**Comment by ArnieX** [comment]
That would be great, thanks ;).
