### ISSUE TITLE
how to flash the wifiswitch

### ISSUE THREAD

**Issue by xfce** [ArnieX/swifitch-software#3]
Hi, I have build your wifiswitch, but I don't know how to flash the board,
I think it use  ATOM with platformio ide,  then build it , download use USBtoSerial cable connect to the ESP8266's UART, AM i right ,or do you have some notes, thanks

**Comment by ArnieX** [comment]
Hi,

did you go through After you build it section here? https://github.com/ArnieX/swifitch#after-you-build-it

You can use modified NodeMCU board for flashing or use other CP2102 UART programmer and this need to be connected to Swifitch header in a right way and you have to use F jumper to get into flash mode. Consult google as well if you have difficulties, search for ESP8266 flashing, all information should apply same to Swifitch.

Thanks for building it and please let me know if you had success with flashing.

BR,

Martin

**Comment by xfce** [comment]
I use ATOM with platformio 
when build the project got bellow error

Project
171205-170900-esp12e
lib
WiFiManager
WiFiManager.cpp
WiFiManager.h
readme.txt
src
main.cpp
.gitignore
.travis.yml
platformio.ini

3.5 s
platformio run
Compiling .pioenvs\esp12e\FrameworkArduino\Esp.o

Compiling .pioenvs\esp12e\FrameworkArduino\FS.o
Compiling .pioenvs\esp12e\FrameworkArduino\HardwareSerial.o
src\main.cpp: In function 'boolean reconnect()':
src\main.cpp:82:23: error: 'mqttConnected' was not declared in this scope
mqttConnected();
^
src\main.cpp:88:150: error: no matching function for call to 'PubSubClient::connect(const char*, char*, char*, const char*, int, bool, const
 char [13])'
if ( client.connect(clientId.c_str(), (char*)mqtt_username, (char*)mqtt_password, mqtt_devicestatus_set_topic.c_str(), 0, false, "disconnect
ed") ) {
^
src\main.cpp:88:150: note: candidates are:
In file included from src\main.cpp:7:0:
C:\Users\tangw\.platformio\lib\MqttConnector_ID310\src/PubSubClient.h:111:9: note: bool PubSubClient::connect(String)
bool connect(String id);
^
C:\Users\tangw\.platformio\lib\MqttConnector_ID310\src/PubSubClient.h:111:9: note:   candidate expects 1 argument, 7 provided
C:\Users\tangw\.platformio\lib\MqttConnector_ID310\src/PubSubClient.h:123:9: note: bool PubSubClient::connect(String, String, uint8_t, bool,
 String)
bool connect(String id, String willTopic, uint8_t willQos, bool willRetain, String willMessage);
^
C:\Users\tangw\.platformio\lib\MqttConnector_ID310\src/PubSubClient.h:123:9: note:   candidate expects 5 arguments, 7 provided
C:\Users\tangw\.platformio\lib\MqttConnector_ID310\src/PubSubClient.h:185:9: note: bool PubSubClient::connect(MQTT::Connect&)
bool connect(MQTT::Connect &conn);
^
C:\Users\tangw\.platformio\lib\MqttConnector_ID310\src/PubSubClient.h:185:9: note:   candidate expects 1 argument, 7 provided
src\main.cpp:90:23: error: 'mqttConnected' was not declared in this scope
mqttConnected();
^
src\main.cpp: In function 'void callback(char*, byte*, unsigned int)':
src\main.cpp:123:9: error: 'blink' was not declared in this scope
blink();
^
src\main.cpp: In function 'void setup()':
src\main.cpp:303:10: error: 'class PubSubClient' has no member named 'setServer'
client.setServer((char*)mqtt_server, atoi(&mqtt_port[0]));
^
src\main.cpp:304:10: error: 'class PubSubClient' has no member named 'setCallback'
client.setCallback(callback);
^
*** [.pioenvs\esp12e\src\main.o] Error 1
 [ERROR] Took 2.82 seconds
 
Linter
Severity 	Provider 	Description	Line 
Git
Initialize C:\Users\tangw\Documents\PlatformIO\Projects\171205-170900-esp12e with a Git repository
Create repository
PIO BuildPlatformIO Home
0 files

**Comment by ArnieX** [comment]
Did you installed those libraries using library manager?

**Comment by ArnieX** [comment]
I'm closing for now. If you still have issues let me know.
