### ISSUE TITLE
PlatformIO project creation

### ISSUE THREAD

**Issue by dicastro** [ArnieX/swifitch-software#7]
I am trying to flash the software in swifitch and I have some doubts.

I have installed PlatformIO (as a Vistual Studio Code plugin). The first thing I was trying to do is to install the 3 required libraries:
- PubSubClient
- ESP8266wifi
- ESPAsyncTCP

**The problem is that the library `ESP8266wifi` is not found in the libraries menu.**

* Do I have to install these libraries before creating any project?
* Do I have to create a project before installing any library?
* Which kind of project do I have to create? What do I have to select in fields `Board` and `Framework`?
<img width="455" alt="platform-io-new-project-screen" src="https://user-images.githubusercontent.com/4919907/36944822-e788606e-1fa3-11e8-81f2-b88b19331487.png">

**Comment by ArnieX** [comment]
Yeah that is probably my mistake. This is default library. Just build and upload. It should download dependencies automatically.

**Comment by dicastro** [comment]
Thank you! I have imported directly the project, built it and upload it.
